export const GET_BATCH = "GET_BATCH";
export const GET_BATCH_PENDING = "GET_BATCH_PENDING";
export const GET_BATCH_ERROR = "GET_BATCH_ERROR";

export const GET_PRINTERS = "GET_PRINTERS";
export const GET_PRINTERS_PENDING = "GET_PRINTERS_PENDING";
export const GET_PRINTERS_ERROR = "GET_PRINTERS_ERROR";
export const GET_LABELS = "GET_LABELS";
