export const GET_BATCH = "GET_BATCH";
export const GET_BATCH_PENDING = "GET_BATCH_PENDING";
export const GET_BATCH_ERROR = "GET_BATCH_ERROR";
export const GET_BATCH_NO_ERROR = "GET_BATCH_NO_ERROR";

export const GET_PRINTERS = "GET_PRINTERS";
export const GET_PRINTERS_PENDING = "GET_PRINTERS_PENDING";
export const GET_PRINTERS_ERROR = "GET_PRINTERS_ERROR";
export const GET_PRINTERS_NO_ERROR = "GET_PRINTERS_NO_ERROR";

export const GET_VIALS = "GET_VIALS";
export const GET_VIALS_PENDING = "GET_VIALS_PENDING";
export const GET_VIALS_ERROR = "GET_VIALS_ERROR";
export const GET_VIALS_NO_ERROR = "GET_VIALS_NO_ERROR";

export const GET_LABEL_RENDERINGS = "GET_LABEL_RENDERINGS";
export const GET_LABEL_RENDERINGS_PENDING = "GET_LABEL_RENDERINGS_PENDING";
export const GET_LABEL_RENDERINGS_ERROR = "GET_LABEL_RENDERINGS_ERROR";
export const GET_LABEL_RENDERINGS_NO_ERROR = "GET_LABEL_RENDERINGS_NO_ERROR";
export const CLEAR_RENDERINGS = "CLEAR_RENDERINGS";
